name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig build test
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig fmt build.zig src --check